# Generated by tools/homebrew-formula.sh in github.com/ShrimpScript/porthole - edit it there.
class Porthole < Formula
  desc "Supervise Claude Code on this computer from your Android phone, over Tailscale"
  homepage "https://porthole-one.vercel.app"
  version "0.37.0"

  on_macos do
    on_arm do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.37.0/portholed-darwin-arm64"
      sha256 "f127cdac2632d127cd43c24cf7c2aace1e197e3eb3da037d87dacd5b6898cc73"
    end
    on_intel do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.37.0/portholed-darwin-amd64"
      sha256 "3118509496e23d0480caf04e0c9d5df767784cd0dea8d23d78bd5b6ac12386a0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.37.0/portholed-linux-arm64"
      sha256 "802978ea77e8d0c366396b4b2530c4d0ce6797fd1af3789a4fef6de7d5b0052b"
    end
    on_intel do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.37.0/portholed-linux-amd64"
      sha256 "78db23bbe30628c51c0b8a8a4864e1bd9d8be7fbd97253c85f0f278d07a2a580"
    end
  end

  depends_on "tmux"

  def install
    bin.install Dir["portholed-*"].first => "portholed"
    # Called as porthole, it starts Claude Code inside tmux, where the phone can reach it.
    bin.install_symlink "portholed" => "porthole"
  end

  def caveats
    <<~EOS
      Start the background service and add the approval hook to Claude Code:
        portholed setup
      Then check everything a phone needs, and pair one:
        portholed doctor
        portholed pair
      Start Claude Code with porthole instead of claude, in your project's folder.
      On a Mac, run portholed setup again after an upgrade: macOS treats each version as
      a new program and asks again about your folders.
    EOS
  end

  test do
    assert_match "portholed #{version}", shell_output("#{bin}/portholed version")
  end
end
