# Generated by tools/homebrew-formula.sh in github.com/ShrimpScript/porthole - edit it there.
class Porthole < Formula
  desc "Supervise Claude Code on this computer from your Android phone, over Tailscale"
  homepage "https://porthole-one.vercel.app"
  version "0.38.0"

  on_macos do
    on_arm do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.38.0/portholed-darwin-arm64"
      sha256 "a83bdac4eaa8cc62ae8e15da52265100e37e26030e8cad3e36e9b104eb3be9ac"
    end
    on_intel do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.38.0/portholed-darwin-amd64"
      sha256 "08debc0129be7dc28de7652918f4153a76a87f83535d5ad5186f5fb750747f48"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.38.0/portholed-linux-arm64"
      sha256 "185980e8b20269043a71f2d25bce4a6af228acba42f9ab754cb8ebe473b75335"
    end
    on_intel do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.38.0/portholed-linux-amd64"
      sha256 "4518fa2e36e4f056a5fca160030117d2bf69483eb0f387d1a1569a208e50d131"
    end
  end

  depends_on "tmux"

  def install
    bin.install Dir["portholed-*"].first => "portholed"
    # Called as porthole, it starts Claude Code inside tmux, where the phone can reach it.
    bin.install_symlink "portholed" => "porthole"
  end

  def caveats
    <<~EOS
      Start the background service and add the approval hook to Claude Code:
        portholed setup
      Then check everything a phone needs, and pair one:
        portholed doctor
        portholed pair
      Start Claude Code with porthole instead of claude, in your project's folder.
      On a Mac, run portholed setup again after an upgrade: macOS treats each version as
      a new program and asks again about your folders.
    EOS
  end

  test do
    assert_match "portholed #{version}", shell_output("#{bin}/portholed version")
  end
end
