# Generated by tools/homebrew-formula.sh in github.com/ShrimpScript/porthole - edit it there.
class Porthole < Formula
  desc "Supervise Claude Code on this computer from your Android phone, over Tailscale"
  homepage "https://porthole-one.vercel.app"
  version "0.32.0"

  on_macos do
    on_arm do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.32.0/portholed-darwin-arm64"
      sha256 "aeae36a1798338aa8014fdf7ae6082e12632dc115870cd425798b46c7dc62075"
    end
    on_intel do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.32.0/portholed-darwin-amd64"
      sha256 "b25b1ac7f4dfea1c73397ada2c51ee6cf89e8ac8a88ad58679bb96abfff41b3d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.32.0/portholed-linux-arm64"
      sha256 "b6c74017cf34ed0db49334afc426b82a1ff78d93e8780d055bdf3608d5182db2"
    end
    on_intel do
      url "https://github.com/ShrimpScript/porthole/releases/download/v0.32.0/portholed-linux-amd64"
      sha256 "a5e8980f808dcd8faa09a1489c347911d4ea7920c770e190b7e7e43e4e8fdbc1"
    end
  end

  depends_on "tmux"

  def install
    bin.install Dir["portholed-*"].first => "portholed"
    # Called as porthole, it starts Claude Code inside tmux, where the phone can reach it.
    bin.install_symlink "portholed" => "porthole"
  end

  def caveats
    <<~EOS
      Start the background service and add the approval hook to Claude Code:
        portholed setup
      Then check everything a phone needs, and pair one:
        portholed doctor
        portholed pair
      Start Claude Code with porthole instead of claude, in your project's folder.
      On a Mac, run portholed setup again after an upgrade: macOS treats each version as
      a new program and asks again about your folders.
    EOS
  end

  test do
    assert_match "portholed #{version}", shell_output("#{bin}/portholed version")
  end
end
